#!/usr/bin/env node
(function () {
    'use strict';

    var program = require('commander'),
        path = require('path'),
        fs = require('fs'),
        Braces = require('./braces');

    program
        .version('0.0.1')
        .usage('[options] <file>')
        .option('-d, --extension-directory <dir>', 'specify a directory to use for extensions')
        .option('-e, --extensions <files>', 'specify a comma separated list of extensions', list)
        .option('-o, --out <file>', 'specify the output file')
        .parse(process.argv);

    if (program.args.length != 1) {
        program.help();
    }

    var inFile = program.args[0];
    var outFile = program.out || getExtensionlessFileName(inFile) + '.html';

    var markup = fs.readFileSync(inFile, 'utf8');

    var extensions = fetchExtensions(program.extensionDirectory, program.extensions);

    var braces = new Braces(extensions);

    var html = braces.parse(markup);
    fs.writeFileSync(outFile, html);

    // Convenience functions:
    function prettyPrintJson(json) {
        return JSON.stringify(json, null, '  ') + '\n';
    }

    function getExtensionlessFileName(fileName) {
        return path.basename(fileName, path.extname(fileName));
    }

    function fetchExtensions(dir, names) {
        dir = dir || ('.' + path.sep);
        names = names || [];

        var extensions = {};
        names.forEach(function (name) {
            extensions[name] = require('.' + path.sep + dir + path.sep + name);
        });

        return extensions;
    }

    function list(val) {
        return val.split(',');
    }
}());
